# This is a basic workflow to help you get started with Actions

name: Minify Files

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build ReactJS
      run: |
        cd dev
        npm cache clean --force
        npm run build
        rm -rf ../static ../robots.txt ../asset-manifest.json ../favicon.ico ../index.html ../logo512.png ../logo192.png ../manifest.json
        mv -f build/* ..

    - name: Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Minify Files" || echo
        git push
